# Generated by Django 4.1.4 on 2022-12-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=16)),
                ('confirm_p', models.CharField(max_length=16)),
            ],
        ),
    ]
